### ISSUE TITLE
Not compatible with monolog < 2.0

### ISSUE THREAD

**Issue by rmikalkenas** [gmponos/monolog-slack#17]
`AbstractSlackAttachmentFormatter` `normalize` and `normalizeException` methods are not compatible with `Monolog\Formatter\NormalizerFormatter` and breaks for monolog versions up to 2.0. 

Possible fix would be to remove `monolog/monolog: ^1.24` version constraint from composer.json and leave just `^2.0`.

**Comment by gmponos** [comment]
I created a PR. can you have a look. :)
